Last login: Thu Mar 13 23:03:35 on ttys000
quartermaster@Q ~ % docker --version
Docker version 27.5.1, build 9f9e405
quartermaster@Q ~ % docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c9c5fd25a1bd: Download complete 
Digest: sha256:7e1a4e2d11e2ac7a8c3f768d4166c2defeb09d2a750b010412b6ea13de1efb19
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

quartermaster@Q ~ % mkdir ~/docker-streamlit-app
cd ~/docker-streamlit-app
quartermaster@Q docker-streamlit-app % nano Dockerfile

  UW PICO 5.09                    File: Dockerfile                    Modified  


# Pythonライブラリをインストール
RUN pip install --no-cache-dir \
    mecab-python3 \
    pandas \
    streamlit
    
# アプリのコードをコピー
COPY . /app   
WORKDIR /app

# Streamlitを実行
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.$
    
    
    




^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   
^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell  
